<header>
  <div class="container">
    <h1 class="logo">Canvas</h1>

    <nav>
      <ul>
        <li id="index"><a href="index.php">Home</a></li>
        <li id="topic"><a href="topic.php">Topic</a></li>
        <li id="quiz"><a href="quiz.php">Quiz</a></li>
        <li id="manage"><a href="manage.php">Manage</a></li>
        <li id="enhancements">
          <a href="enhancements.html">Enhancements</a>
        </li>
        <li id="enhancements2">
          <a href="enhancements2.html">Enhancements 2</a>
        </li>
      </ul>
    </nav>
  </div>
</header>
